/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as ScreenCodeRouteImport } from './routes/screen.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenCodeRoute = ScreenCodeRouteImport.update({
  id: '/screen/$code',
  path: '/screen/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play/$code': typeof PlayCodeRoute
  '/screen/$code': typeof ScreenCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play/$code': typeof PlayCodeRoute
  '/screen/$code': typeof ScreenCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play/$code': typeof PlayCodeRoute
  '/screen/$code': typeof ScreenCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play/$code' | '/screen/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play/$code' | '/screen/$code'
  id: '__root__' | '/' | '/play/$code' | '/screen/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayCodeRoute: typeof PlayCodeRoute
  ScreenCodeRoute: typeof ScreenCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen/$code': {
      id: '/screen/$code'
      path: '/screen/$code'
      fullPath: '/screen/$code'
      preLoaderRoute: typeof ScreenCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayCodeRoute: PlayCodeRoute,
  ScreenCodeRoute: ScreenCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
